# CLASE 3

In [2]:
import numpy as np



In [3]:
array = np.arange(27)

In [4]:
array = array.reshape(3,3,3)
array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
array.dtype

dtype('int64')

In [6]:
type(array)

numpy.ndarray

In [7]:
array.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [8]:
array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
np.array([[1,2,4,5,6,7],[1,2,4,5,6,7]])

array([[1, 2, 4, 5, 6, 7],
       [1, 2, 4, 5, 6, 7]])

In [11]:
np.linspace(1,20,20)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [12]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [13]:
b = np.arange(10,30,2)
b.resize(2,2)

In [14]:
a=np.random.random(10)
a.resize(2,2)

In [15]:
b@a # producto entre matrices

array([[6.47738845, 3.02829864],
       [8.96634797, 4.04596868]])

In [16]:
a.shape

(2, 2)

In [17]:
b.shape

(2, 2)

In [18]:
np.random.uniform(0,10,(4,4))

array([[2.1480783 , 7.67060434, 2.30998083, 8.13378849],
       [0.59748731, 8.25788451, 8.36210499, 9.6303141 ],
       [5.57704964, 5.20964325, 4.80837361, 4.49998509],
       [3.13921516, 3.18197315, 7.85467385, 8.08225551]])

In [19]:
np.random.random((4,4))

array([[0.81594326, 0.30686314, 0.08862616, 0.18315901],
       [0.79053589, 0.41319743, 0.43773508, 0.98774815],
       [0.26020614, 0.73382851, 0.23199386, 0.49419562],
       [0.60632639, 0.69679198, 0.19741513, 0.84091809]])

In [20]:
a = np.arange(10)

In [21]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b = a.view()

In [23]:
b = b.reshape(5,2)

In [24]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [25]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b[2,1]=1000

In [27]:
a

array([   0,    1,    2,    3,    4, 1000,    6,    7,    8,    9])

In [28]:
import scipy as sp

In [29]:
sp

<module 'scipy' from '/Users/csuarezgurruchaga/opt/anaconda3/envs/UDESA01/lib/python3.6/site-packages/scipy/__init__.py'>

# CLASE 4

In [31]:
import pandas as pd

In [58]:
serie = pd.Series(['susana','martina','sofia'], index = ['primera','segunda','tercera'])
serie

primera     susana
segunda    martina
tercera      sofia
dtype: object

In [33]:
pd.Series({'primera':'susana','segunda':'martina','tercera':'sofia'})

primera     susana
segunda    martina
tercera      sofia
dtype: object

In [35]:
df= pd.DataFrame({'meses':['ENERO','FEBRERO','MARZO','ABRIL'],'NUMEROS':[1,2,3,4],'INICIAL':['E','F','M','A']})
df

meses  NUMEROS INICIAL
0    ENERO        1       E
1  FEBRERO        2       F
2    MARZO        3       M
3    ABRIL        4       A

In [36]:
df.meses

0      ENERO
1    FEBRERO
2      MARZO
3      ABRIL
Name: meses, dtype: object

In [43]:
type(df.NUMEROS)

pandas.core.series.Series

In [42]:
df.NUMEROS.dtype

dtype('int64')

In [44]:
df.columns

Index(['meses', 'NUMEROS', 'INICIAL'], dtype='object')

In [45]:
df.values

array([['ENERO', 1, 'E'],
       ['FEBRERO', 2, 'F'],
       ['MARZO', 3, 'M'],
       ['ABRIL', 4, 'A']], dtype=object)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   meses    4 non-null      object
 1   NUMEROS  4 non-null      int64 
 2   INICIAL  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [47]:
df.head()

meses  NUMEROS INICIAL
0    ENERO        1       E
1  FEBRERO        2       F
2    MARZO        3       M
3    ABRIL        4       A

In [48]:
df.tail()

meses  NUMEROS INICIAL
0    ENERO        1       E
1  FEBRERO        2       F
2    MARZO        3       M
3    ABRIL        4       A

In [49]:
df.sample()

meses  NUMEROS INICIAL
1  FEBRERO        2       F

In [57]:
df.iloc[:,:3]

meses  NUMEROS INICIAL
0    ENERO        1       E
1  FEBRERO        2       F
2    MARZO        3       M
3    ABRIL        4       A

In [64]:
serie.to_frame()

0
primera   susana
segunda  martina
tercera    sofia

In [70]:
df.shape

(4, 3)

In [72]:
df.plot.scatter

<bound method PlotAccessor.scatter of <pandas.plotting._core.PlotAccessor object at 0x7f99100d0b00>>

In [77]:
df = pd.read_csv('chipotle.tsv', sep='\t', index_col= 'order_id')

In [78]:
df

quantity                              item_name  \
order_id                                                    
1                1           Chips and Fresh Tomato Salsa   
1                1                                   Izze   
1                1                       Nantucket Nectar   
1                1  Chips and Tomatillo-Green Chili Salsa   
2                2                           Chicken Bowl   
...            ...                                    ...   
1833             1                          Steak Burrito   
1833             1                          Steak Burrito   
1834             1                     Chicken Salad Bowl   
1834             1                     Chicken Salad Bowl   
1834             1                     Chicken Salad Bowl   

                                         choice_description item_price  
order_id                                                                
1                                                       NaN     $2.39   
1                                              [Clementine]     $3.39   
1                                                   [Apple]     $3.39   
1                                                       NaN     $2.39   
2         [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
...                                                     ...        ...  
1833      [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
1833      [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
1834      [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
1834      [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
1834      [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75   

[4622 rows x 4 columns]

In [83]:
groupby_1 = df.groupby('item_name').agg({'quantity':['min','mean','max'], 'item_price':[lambda x: str(x).strip('$')]})
groupby_1.head()

quantity                \
                           min      mean max   
item_name                                      
6 Pack Soft Drink            1  1.018519   2   
Barbacoa Bowl                1  1.000000   1   
Barbacoa Burrito             1  1.000000   1   
Barbacoa Crispy Tacos        1  1.090909   2   
Barbacoa Salad Bowl          1  1.000000   1   

                                                              item_price  
                                                                <lambda>  
item_name                                                                 
6 Pack Soft Drink      129      $6.49 \n148      $6.49 \n154      $6....  
Barbacoa Bowl          19      $11.75 \n27      $11.75 \n42       $9....  
Barbacoa Burrito       11       $8.99 \n36       $9.25 \n53       $9....  
Barbacoa Crispy Tacos  75      $11.75 \n110      $9.25 \n186     $11....  
Barbacoa Salad Bowl    501     $11.89 \n541     $11.89 \n576      $9....

In [92]:
groupby_1['quantity', 'max'].head()

item_name
6 Pack Soft Drink        2
Barbacoa Bowl            1
Barbacoa Burrito         1
Barbacoa Crispy Tacos    2
Barbacoa Salad Bowl      1
Name: (quantity, max), dtype: int64

In [93]:
''' 
PIVOT_TABLE a partir de un dataframe
que columna va a pasar como index
que columna va a pasar como index
que columna queres usar para los valores que contendra la pivot table

Yo la utilizo cuando quiero informacion de una columna contra otra columna
'''

'que columna va a pasar como index\nque columna va a pasar como index\nque columna queres usar para calcular'